commerce_payment.commerce_payment_gateway.plugin.invoice_commerce:
  type: commerce_payment_gateway_configuration
  mapping:
      api_key:
        type: string
        label: 'API Key'
      login:
        type: string
        label: 'Login'
      terminal:
        type: string
        label: 'Terminal ID'